-- schema.sql
-- Generated by Architect agent for clowforge-dashboard
-- 
-- IMPORTANT: This file contains ONLY dashboard-specific tables.
-- The forge_projects, forge_runs, and forge_tasks tables already exist
-- and must NOT be modified by this migration.

-- ============================================================
-- EXTENSIONS
-- ============================================================
-- Already enabled in ClowPaco project, but safe to re-run
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ============================================================
-- TYPES
-- ============================================================
CREATE TYPE dashboard_role AS ENUM ('admin', 'viewer');

-- ============================================================
-- FUNCTIONS
-- ============================================================
-- Auto-update updated_at timestamp
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Create dashboard user profile on auth signup
CREATE OR REPLACE FUNCTION handle_dashboard_user_created()
RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO public.dashboard_users (id, email, full_name, role)
    VALUES (
        NEW.id,
        NEW.email,
        COALESCE(NEW.raw_user_meta_data->>'full_name', split_part(NEW.email, '@', 1)),
        'viewer'  -- Default role, admin must upgrade manually
    );
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- ============================================================
-- TABLES (Dashboard-specific only)
-- ============================================================

-- Dashboard users (extends auth.users for dashboard-specific data)
CREATE TABLE IF NOT EXISTS dashboard_users (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    
    email VARCHAR(255) NOT NULL,
    full_name VARCHAR(100),
    role dashboard_role DEFAULT 'viewer' NOT NULL,
    
    -- Preferences
    theme VARCHAR(10) DEFAULT 'system',  -- 'light', 'dark', 'system'
    notifications_enabled BOOLEAN DEFAULT true
);

CREATE INDEX IF NOT EXISTS idx_dashboard_users_email ON dashboard_users (email);

-- Dashboard settings (key-value store for global settings)
CREATE TABLE IF NOT EXISTS dashboard_settings (
    key VARCHAR(50) PRIMARY KEY,
    value JSONB NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT now() NOT NULL
);

-- Deployment logs (track manual deploys triggered via dashboard)
CREATE TABLE IF NOT EXISTS deployment_logs (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    
    project_id UUID NOT NULL,  -- References forge_projects(id) but no FK to avoid tight coupling
    run_id UUID,               -- Optional, references forge_runs(id)
    
    triggered_by UUID NOT NULL REFERENCES dashboard_users(id) ON DELETE SET NULL,
    
    action VARCHAR(20) NOT NULL,  -- 'deploy_preview', 'deploy_production', 'rollback'
    target_url TEXT,
    
    status VARCHAR(20) DEFAULT 'pending' NOT NULL,  -- 'pending', 'success', 'failed'
    vercel_deployment_id VARCHAR(100),
    error_message TEXT,
    
    completed_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_deployment_logs_project ON deployment_logs (project_id);
CREATE INDEX IF NOT EXISTS idx_deployment_logs_created ON deployment_logs (created_at DESC);

-- ============================================================
-- VIEWS (Cost aggregations from existing forge_* tables)
-- ============================================================

-- Monthly cost summary
CREATE OR REPLACE VIEW v_monthly_costs AS
SELECT
    date_trunc('month', r.created_at) AS month,
    COUNT(DISTINCT r.project_id) AS projects_count,
    COUNT(r.id) AS runs_count,
    COALESCE(SUM(r.cost_usd), 0) AS total_cost_usd,
    COALESCE(SUM(t.input_tokens), 0) AS total_input_tokens,
    COALESCE(SUM(t.output_tokens), 0) AS total_output_tokens
FROM forge_runs r
LEFT JOIN forge_tasks t ON t.run_id = r.id
GROUP BY date_trunc('month', r.created_at)
ORDER BY month DESC;

-- Per-project cost summary
CREATE OR REPLACE VIEW v_project_costs AS
SELECT
    p.id AS project_id,
    p.name AS project_name,
    COUNT(r.id) AS runs_count,
    COALESCE(SUM(r.cost_usd), 0) AS total_cost_usd,
    MAX(r.created_at) AS last_run_at
FROM forge_projects p
LEFT JOIN forge_runs r ON r.project_id = p.id
GROUP BY p.id, p.name
ORDER BY total_cost_usd DESC;

-- Run details with task aggregation
CREATE OR REPLACE VIEW v_run_details AS
SELECT
    r.id AS run_id,
    r.project_id,
    p.name AS project_name,
    r.status,
    r.started_at,
    r.completed_at,
    EXTRACT(EPOCH FROM (r.completed_at - r.started_at)) * 1000 AS duration_ms,
    r.cost_usd,
    r.error_message,
    COUNT(t.id) AS tasks_count,
    COUNT(t.id) FILTER (WHERE t.status = 'completed') AS tasks_completed,
    COUNT(t.id) FILTER (WHERE t.status = 'failed') AS tasks_failed,
    array_agg(DISTINCT t.agent) FILTER (WHERE t.agent IS NOT NULL) AS agents_used
FROM forge_runs r
JOIN forge_projects p ON p.id = r.project_id
LEFT JOIN forge_tasks t ON t.run_id = r.id
GROUP BY r.id, r.project_id, p.name, r.status, r.started_at, r.completed_at, r.cost_usd, r.error_message
ORDER BY r.created_at DESC;

-- ============================================================
-- TRIGGERS
-- ============================================================

-- Updated_at triggers for dashboard tables
CREATE TRIGGER update_dashboard_users_updated_at
    BEFORE UPDATE ON dashboard_users FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_dashboard_settings_updated_at
    BEFORE UPDATE ON dashboard_settings FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- Auto-create dashboard user on auth signup
-- Drop first in case it exists
DROP TRIGGER IF EXISTS on_auth_user_created_dashboard ON auth.users;
CREATE TRIGGER on_auth_user_created_dashboard
    AFTER INSERT ON auth.users FOR EACH ROW
    EXECUTE FUNCTION handle_dashboard_user_created();

-- ============================================================
-- ROW LEVEL SECURITY
-- ============================================================

-- Dashboard users: users can read all (small team), update own
ALTER TABLE dashboard_users ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Authenticated users can view all dashboard users"
    ON dashboard_users FOR SELECT
    USING (auth.role() = 'authenticated');

CREATE POLICY "Users can update own profile"
    ON dashboard_users FOR UPDATE
    USING (auth.uid() = id)
    WITH CHECK (auth.uid() = id);

-- Dashboard settings: all authenticated can read, admin can write
ALTER TABLE dashboard_settings ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Authenticated users can read settings"
    ON dashboard_settings FOR SELECT
    USING (auth.role() = 'authenticated');

-- REQUIRES: service_role (admin operations via API)
CREATE POLICY "Service role manages settings"
    ON dashboard_settings FOR ALL
    USING (auth.role() = 'service_role');

-- Deployment logs: all authenticated can read, insert requires auth
ALTER TABLE deployment_logs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Authenticated users can view deployment logs"
    ON deployment_logs FOR SELECT
    USING (auth.role() = 'authenticated');

CREATE POLICY "Authenticated users can create deployment logs"
    ON deployment_logs FOR INSERT
    WITH CHECK (auth.role() = 'authenticated');

-- REQUIRES: service_role (for status updates from webhooks)
CREATE POLICY "Service role updates deployment logs"
    ON deployment_logs FOR UPDATE
    USING (auth.role() = 'service_role');

-- ============================================================
-- RLS POLICIES FOR EXISTING FORGE_* TABLES
-- ============================================================
-- These tables already have RLS. Adding SELECT policies for dashboard users.
-- Run these manually if dashboard users can't query forge_* tables.

-- NOTE: Only add these if forge_* tables don't already have open SELECT policies
/*
CREATE POLICY "Dashboard users can read forge_projects"
    ON forge_projects FOR SELECT
    USING (auth.role() = 'authenticated');

CREATE POLICY "Dashboard users can read forge_runs"
    ON forge_runs FOR SELECT
    USING (auth.role() = 'authenticated');

CREATE POLICY "Dashboard users can read forge_tasks"
    ON forge_tasks FOR SELECT
    USING (auth.role() = 'authenticated');
*/

-- ============================================================
-- SEED DATA
-- ============================================================

-- Default settings
INSERT INTO dashboard_settings (key, value) VALUES
    ('cost_alert_threshold_usd', '10'),
    ('default_poll_interval_ms', '30000'),
    ('realtime_enabled', 'true')
ON CONFLICT (key) DO NOTHING;
